### ISSUE TITLE
可否出一个编译配置说明文档

### ISSUE THREAD

**Issue by sunshine-lcc** [lizhirui/K210-Linux0.11#3]
不太清楚这个项目是怎么把它编译出来的，请问作者能否出个文档，把编译过程和需要的依赖库讲讲呢？

**Comment by lizhirui** [comment]
1、在真实机或者虚拟机中安装一个centos6.4
2、保证centos6.4中包含mkfs和mount且都支持minix 2文件系统，并包含有glibc库
3、使用Visual Studio 2019打开解决方案，依次编译其中的bin2aout、depfileconvert、pathconv、run工程，对于run工程，要先打开tools_src/run/Program.cs，找到"python kflash.py -B goE -b 1500000 -s -p COM22 ..\\src_test\\image.bin"与“plink -serial COM22 -sercfg 115200,8,1,N,N -mem”，将这两处中的COM22修改为K210板子连接电脑后正确的COM口
4、直接从K210官方的IDE中拷贝出整个riscv-unknown-elf编译工具链，然后覆盖到tools目录下，保证tools目录下存在且仅存在bin、include、lib、libexec、riscv64-unknown-elf、share这六个目录，然后将编译好的bin2aout.exe和run.exe复制到tools目录下，将编译好的depfileconvert.exe和pathconv.exe复制到tools\bin目录下，从网上下载一个plink.exe放置在tools目录下
5、修改src_test\Makefile文件中的REMOTE_HOST项，将其设置为对应的主机，同时配置好ssh的公钥登录，或者将明文密码直接写于此，从https://git-scm.com/downloads处下载windows版本的git并安装，将Makefile文件中的SCP和SSH项指向git安装目录中的相应文件，将ROOTPATH项指向源代码解压的路径中的src_test目录
6、修改tools\cc.bat，将期中的ROOTPATH路径指向源代码目录中的src_test目录
7、保证centos6.4系统处于在线状态并正确连接局域网且可以和Windows主机正常保持网络通信，在Visual Studio 2019中对K210-Linux0.11-VS工程执行编译即可，最终会在src_test目录下生成system.bin、rootfs.bin与image.bin，只需烧录image.bin即可，也可通过直接按F5键实现运行

**Comment by Luchangcheng2333** [comment]
> 1、在真实机或者虚拟机中安装一个centos6.4
> 2、保证centos6.4中包含mkfs和mount且都支持minix 2文件系统，并包含有glibc库
> 3、使用Visual Studio 2019打开解决方案，依次编译其中的bin2aout、depfileconvert、pathconv、run工程，对于run工程，要先打开tools_src/run/Program.cs，找到"python kflash.py -B goE -b 1500000 -s -p COM22 ..\src_test\image.bin"与“plink -serial COM22 -sercfg 115200,8,1,N,N -mem”，将这两处中的COM22修改为K210板子连接电脑后正确的COM口
> 4、直接从K210官方的IDE中拷贝出整个riscv-unknown-elf编译工具链，然后覆盖到tools目录下，保证tools目录下存在且仅存在bin、include、lib、libexec、riscv64-unknown-elf、share这六个目录，然后将编译好的bin2aout.exe和run.exe复制到tools目录下，将编译好的depfileconvert.exe和pathconv.exe复制到tools\bin目录下，从网上下载一个plink.exe放置在tools目录下
> 5、修改src_test\Makefile文件中的REMOTE_HOST项，将其设置为对应的主机，同时配置好ssh的公钥登录，或者将明文密码直接写于此，从[https://git-scm.com/downloads处下载windows版本的git并安装，将Makefile文件中的SCP和SSH项指向git安装目录中的相应文件，将ROOTPATH项指向源代码解压的路径中的src_test目录](https://git-scm.com/downloads%E5%A4%84%E4%B8%8B%E8%BD%BDwindows%E7%89%88%E6%9C%AC%E7%9A%84git%E5%B9%B6%E5%AE%89%E8%A3%85%EF%BC%8C%E5%B0%86Makefile%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84SCP%E5%92%8CSSH%E9%A1%B9%E6%8C%87%E5%90%91git%E5%AE%89%E8%A3%85%E7%9B%AE%E5%BD%95%E4%B8%AD%E7%9A%84%E7%9B%B8%E5%BA%94%E6%96%87%E4%BB%B6%EF%BC%8C%E5%B0%86ROOTPATH%E9%A1%B9%E6%8C%87%E5%90%91%E6%BA%90%E4%BB%A3%E7%A0%81%E8%A7%A3%E5%8E%8B%E7%9A%84%E8%B7%AF%E5%BE%84%E4%B8%AD%E7%9A%84src_test%E7%9B%AE%E5%BD%95)
> 6、修改tools\cc.bat，将期中的ROOTPATH路径指向源代码目录中的src_test目录
> 7、保证centos6.4系统处于在线状态并正确连接局域网且可以和Windows主机正常保持网络通信，在Visual Studio 2019中对K210-Linux0.11-VS工程执行编译即可，最终会在src_test目录下生成system.bin、rootfs.bin与image.bin，只需烧录image.bin即可，也可通过直接按F5键实现运行

非常感谢！还有请问这个能在QEMU上面跑嘛？

**Comment by sunshine-lcc** [comment]
> 1、在真实机或者虚拟机中安装一个centos6.4
> 2、保证centos6.4中包含mkfs和mount且都支持minix 2文件系统，并包含有glibc库
> 3、使用Visual Studio 2019打开解决方案，依次编译其中的bin2aout、depfileconvert、pathconv、run工程，对于run工程，要先打开tools_src/run/Program.cs，找到"python kflash.py -B goE -b 1500000 -s -p COM22 ..\src_test\image.bin"与“plink -serial COM22 -sercfg 115200,8,1,N,N -mem”，将这两处中的COM22修改为K210板子连接电脑后正确的COM口
> 4、直接从K210官方的IDE中拷贝出整个riscv-unknown-elf编译工具链，然后覆盖到tools目录下，保证tools目录下存在且仅存在bin、include、lib、libexec、riscv64-unknown-elf、share这六个目录，然后将编译好的bin2aout.exe和run.exe复制到tools目录下，将编译好的depfileconvert.exe和pathconv.exe复制到tools\bin目录下，从网上下载一个plink.exe放置在tools目录下
> 5、修改src_test\Makefile文件中的REMOTE_HOST项，将其设置为对应的主机，同时配置好ssh的公钥登录，或者将明文密码直接写于此，从[https://git-scm.com/downloads处下载windows版本的git并安装，将Makefile文件中的SCP和SSH项指向git安装目录中的相应文件，将ROOTPATH项指向源代码解压的路径中的src_test目录](https://git-scm.com/downloads%E5%A4%84%E4%B8%8B%E8%BD%BDwindows%E7%89%88%E6%9C%AC%E7%9A%84git%E5%B9%B6%E5%AE%89%E8%A3%85%EF%BC%8C%E5%B0%86Makefile%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84SCP%E5%92%8CSSH%E9%A1%B9%E6%8C%87%E5%90%91git%E5%AE%89%E8%A3%85%E7%9B%AE%E5%BD%95%E4%B8%AD%E7%9A%84%E7%9B%B8%E5%BA%94%E6%96%87%E4%BB%B6%EF%BC%8C%E5%B0%86ROOTPATH%E9%A1%B9%E6%8C%87%E5%90%91%E6%BA%90%E4%BB%A3%E7%A0%81%E8%A7%A3%E5%8E%8B%E7%9A%84%E8%B7%AF%E5%BE%84%E4%B8%AD%E7%9A%84src_test%E7%9B%AE%E5%BD%95)
> 6、修改tools\cc.bat，将期中的ROOTPATH路径指向源代码目录中的src_test目录
> 7、保证centos6.4系统处于在线状态并正确连接局域网且可以和Windows主机正常保持网络通信，在Visual Studio 2019中对K210-Linux0.11-VS工程执行编译即可，最终会在src_test目录下生成system.bin、rootfs.bin与image.bin，只需烧录image.bin即可，也可通过直接按F5键实现运行

非常感谢！还想请教下这个内核怎么在QEMU下面进行调试呢？
